title: Something Witty
subs:
        - List of subtitles
        - Randomly selected
        - On each page
author: Rifle Ravi
url:
        domain: example.com
        path: /
        email: mailto@example.com
accounts:
        github: github
        twitter: twitter
btc: 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa
# Add links to pages here
nav_links:
        - name: Posts
          url: /index.html
        - name: About Me
          url: /about.html

